import { COMPS } from ".";

export interface MediaInterface {
  slug: COMPS;
  title: string;
  src: string;
  b64: string;
  aspectRatio: string;
  rText?: "top-black" | "bottom-black" | "top-white" | "bottom-white";
}

export const MEDIA_DATA: MediaInterface[] = [
  {
    slug: COMPS.DYNAMIC_SCROLL_ISLAND,
    title: "Dynamic Scroll Island TOC",
    src: "https://cdn.daddy.design/dynamic-scroll-island-toc.mp4",
    b64: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAArwCSAAD//gAPTGF2YzYwLjMuMTAwAP/bAEMACAQEBAQEBQUFBQUFBgYGBgYGBgYGBgYGBgcHBwgICAcHBwYGBwcICAgICQkJCAgICAkJCgoKDAwLCw4ODhERFP/EAGkAAQEBAAAAAAAAAAAAAAAAAAQDBwEBAQAAAAAAAAAAAAAAAAAABAUQAAICAQMDBQEAAAAAAAAAAAIBBAMFAAYRMRIhM0EiUQcTEQACAgIBBQEAAAAAAAAAAAACAQMhBBEAcTFhBRMS/8AAEQgACgAKAwEiAAIRAAMRAP/aAAwDAQACEQMRAD8AZ+YYPCZDbW2ZM/C4Oa7cfGMCvxMewjZ9ytKVcfLkk36Taf8APjjWJZSsq8nNAPiIybxEV4QpWEkkvpLVsRujcsWqHRRm8vRTSHZTVVPlV11B17awG1CA8+wpLQrTM7bCIiIiMm22222/LbfVvVr0UmV988zyJJBMwYgTJqO5NoWydOqWlXGYEDMp5CkN/olT7J23rrtV45//2Q==",
    aspectRatio: "1/1",
    rText: "bottom-white",
  },

  {
    slug: COMPS.COOL_CHECKBOX,
    title: "Cool checkbox",
    src: "https://cdn.daddy.design/cool-checkbox.mp4",
    b64: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAABwAGAAD//gAPTGF2YzYwLjMuMTAwAP/bAEMACAQEBAQEBQUFBQUFBgYGBgYGBgYGBgYGBgcHBwgICAcHBwYGBwcICAgICQkJCAgICAkJCgoKDAwLCw4ODhERFP/EAGwAAQEBAAAAAAAAAAAAAAAAAAcEBgEBAQAAAAAAAAAAAAAAAAAABAUQAAICAAQDCQEAAAAAAAAAAAIBAwQGBQAhEhMRUWGRkkHRMRYHIxEAAgICAwEBAQAAAAAAAAAAAQIDEQQSIQAFUTFB/8AAEQgACgAKAwEiAAIRAAMRAP/aAAwDAQACEQMRAD8A3/57gDCt3B1CfMMgoW7JDc5tmaHikJhZmEeJ9fQUKXctGX1qd78svDSFYAAmMRERXVbJJLf52XbqtV66S/jF5B9tXvO9GbHyc52LyiWXZVaRqiGznVbv7/APzpZoQyRAUuq0TQ54Hf/Z",
    aspectRatio: "1/1",
  },
  {
    slug: COMPS.ANIMATED_BLUR_TESTIMONIALS,
    title: "Animated Blur Testimonials",
    src: "https://cdn.daddy.design/animated-blur-testimonials.mp4",
    b64: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD//gAPTGF2YzYwLjMuMTAwAP/bAEMACAQEBAQEBQUFBQUFBgYGBgYGBgYGBgYGBgcHBwgICAcHBwYGBwcICAgICQkJCAgICAkJCgoKDAwLCw4ODhERFP/EAFgAAAMBAAAAAAAAAAAAAAAAAAADAQcBAQAAAAAAAAAAAAAAAAAAAAAQAAICAgIDAQAAAAAAAAAAAAIBABEhAxIEcnFRQxEBAAAAAAAAAAAAAAAAAAAAAP/AABEIAAoADgMBIgACEQADEQD/2gAMAwEAAhEDEQA/AN05doezt/XVQ8AQCDB1ls2dkn4qo0CZLIsH8bTfvEsIH//Z",
    aspectRatio: "7/5",
  },
  {
    slug: COMPS.FAMILY_BUTTON,
    title: "Family status indicator",
    src: "https://cdn.daddy.design/family-button.mp4",
    b64: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAIwAhAAD//gAPTGF2YzYwLjMuMTAwAP/bAEMACAQEBAQEBQUFBQUFBgYGBgYGBgYGBgYGBgcHBwgICAcHBwYGBwcICAgICQkJCAgICAkJCgoKDAwLCw4ODhERFP/EAF0AAQEBAAAAAAAAAAAAAAAAAAADBwEBAAAAAAAAAAAAAAAAAAAAARAAAwABBAMBAAAAAAAAAAAAAAECEaEDEiEkgwRSEQEBAQADAQAAAAAAAAAAAAABAgAhwWES/8AAEQgACgAWAwEiAAIRAAMRAP/aAAwDAQACEQMRAD8A3m6qZzMc3+cpavomt76m14lL27fWpUCUBzI+v10mKml4up8Ce5cAAZ3/2Q==",
    aspectRatio: "11/5",
  },

  {
    slug: COMPS.GOOEY_MENU,
    title: "Gooey Menu",
    src: "https://cdn.daddy.design/gooey-menu.mp4",
    b64: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAIwAiAAD//gAPTGF2YzYwLjMuMTAwAP/bAEMACAQEBAQEBQUFBQUFBgYGBgYGBgYGBgYGBgcHBwgICAcHBwYGBwcICAgICQkJCAgICAkJCgoKDAwLCw4ODhERFP/EAGAAAQEBAQEAAAAAAAAAAAAAAAAHAwQGAQEAAAAAAAAAAAAAAAAAAAAAEAABBAIABAcBAAAAAAAAAAABEQMCBAUABzESIRZCCFEjBiJiEQEAAAAAAAAAAAAAAAAAAAAA/8AAEQgACgAiAwEiAAIRAAMRAP/aAAwDAQACEQMRAD8AvW5X3bTFG27Tri3ZbrvOVqxcDIsPRbkW2S7IGLYcmBAzPaKqd11oTaPEP1CkRJ4P1FPSo8R0xz6F8xTmfdF/gr7v61dzWRwGOt5vGRw2SeYjO5j4vxsxquqfjD0PzLskuyoqKU3u1oNa1of/2Q==",
    aspectRatio: "17/5",
  },
];
